Repository McAle16/process-wallpaper-multicolor, pull requests merged in 2022-10, with the labels that each got.

#34 Remove color
  colors.py
Labels: hacktoberfest-accepted

#35 Remove color 2
  colors.py
Labels: hacktoberfest-accepted

#36 Add blue
  colors.py
Labels: hacktoberfest-accepted

#37 Add violet
  colors.py
Labels: hacktoberfest-accepted

#39 Update colors.py
  colors.py
Labels: hacktoberfest-accepted

#40 Update setup.sh
  setup.sh
Labels: documentation, hacktoberfest-accepted

#41 Update updateWallpaper.sh
  updateWallpaper.sh
Labels: enhancement, hacktoberfest-accepted

#44 #feeded color
  colors.py
Labels: hacktoberfest-accepted

#45 #beefed color
  colors.py
Labels: hacktoberfest-accepted

#46 More word colors from https://hex-triplet-words.glitch.me
  colors.py
Labels: hacktoberfest-accepted
